export const DRINKS = {
  FETCH: 'FETCH_DRINKS',
  PERSIST: 'PERSIST_DRINKS',
  TYPE: 'UPDATE_DRINK_TYPE',
}

export const DRINKSINFO = {
  FETCH: 'FETCH_DRINK_INFO',
  PERSIST: 'UPERSIST_DRINK_INFO',
}
