export const TEAMS = {
  FETCH: 'FETCH_TEAMS',
  PERSIST: 'PERSIST_TEAMS',
}

export const FAVORITE_TEAMS = {
  ADD: 'ADD_FAVORITE_TEAM',
  REMOVE: 'REMOVE_FAVORITE_TEAM',
  SHOW_ADD_NOTIFICATION: 'SHOW_ADD_FAVORITE_TEAM_NOTIFICATION',
  HIDE_ADD_NOTIFICATION: 'HIDE_ADD_FAVORITE_TEAM_NOTIFICATION',
}

export const PLAYERS = {
  FETCH: 'FETCH_PLAYERS',
  PERSIST: 'PERSIST_PLAYERS',
}

export default undefined
